services:
  be:
    restart: unless-stopped
    build:
      context: ../backend
      dockerfile: Dockerfile
    env_file:
      - ../backend/.env
    ports:
      - "127.0.0.1:8000:8000"

  fe:
    restart: unless-stopped
    build:
      context: ../frontend
      dockerfile: Dockerfile
    env_file:
      - ../frontend/.env

  ai:
    restart: unless-stopped
    build:
      context: ../aiagent
      dockerfile: Dockerfile
    env_file:
      - ../aiagent/.env

  caddy:
    image: caddy:2.6.4-alpine
    container_name: caddy
    restart: unless-stopped
    depends_on:
      - be
      - fe
      - ai
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
