"""Write the engine defaults the browser port reads (web/src/engine/defaults.generated.ts).

The Python package is the single source of truth: every threshold the web
engine uses is copied from ``gaze_lab.config.load_config()`` here, never typed by
hand in TypeScript.  ``tests/lab/test_web_engine_sources.py`` fails when this file
is stale, so a YAML change cannot silently leave the browser behind.

Run after changing a YAML in ``configs/``::

    uv run python tools/export_config.py
"""

from __future__ import annotations

import json
from dataclasses import asdict
from pathlib import Path
from typing import Any, Dict

PROJECT = Path(__file__).resolve().parents[1]
OUT = PROJECT / "web" / "src" / "engine" / "defaults.generated.ts"

#: Only what the head-pose path needs; eye-backbone and offline keys stay in Python.
_KEEP = {
    "preprocess": (
        "analysis_fps", "num_faces", "min_face_confidence", "min_face_area_ratio",
        "min_eye_openness", "border_tolerance_px",
    ),
    "placement": ("min_samples_per_target", "min_separation", "min_delta_deg", "anchor_min_axis_dominance"),
    "calibration": (
        "min_samples_per_class", "min_loo_accuracy", "p_max_threshold", "margin_threshold",
        "check_pitch_ordering", "target_good_frames", "cue_settle_ms", "cue_timeout_ms",
        "min_sample_confidence", "max_head_deviation_deg", "outlier_k", "cue_direction_gate",
        "cue_min_up_deg", "cue_min_down_deg", "cue_screen_radius_deg", "cue_max_side_deg",
        "cue_confirm_frames", "cue_confirm_deg", "sigma_min_deg",
        "sigma_scale", "screen_aspect", "script_width_fraction", "script_height_fraction",
        "camera_halfwidth_deg", "other_field_yaw_deg", "other_field_pitch_deg", "other_margin_deg",
        "screen_min_halfwidth_deg", "screen_max_halfwidth_deg", "prior_camera",
        "prior_screen", "prior_bottom", "prior_other", "head_away_yaw_deg", "head_away_pitch_deg",
        "min_anchor_separation", "merge_inseparable_screen", "reanchor_frames",
        "reanchor_max_shift_deg", "reanchor_timeout_ms",
    ),
    "preconditions": None,  # every field
    "condition": None,
    "evidence": None,
    "sweep": None,
}


def build() -> Dict[str, Any]:
    from gaze_lab.config import load_config
    from gaze_lab.runtime.version import CLASSIFIER_VERSIONS, MODEL_VERSION

    cfg = load_config()
    out: Dict[str, Any] = {
        "_generated_by": "tools/export_config.py -- do not edit by hand",
        "config_hash": cfg.hash(),
        "version": {
            "modelVersion": MODEL_VERSION,
            "gazeBackbone": "head_pose",
            "gazeClassifier": CLASSIFIER_VERSIONS["reference"],
        },
    }
    for section, keys in _KEEP.items():
        values = asdict(getattr(cfg, section))
        out[section] = values if keys is None else {k: values[k] for k in keys}
    return out


def render() -> str:
    # A TypeScript module rather than JSON: the frontend compiles without
    # ``resolveJsonModule``, and this file has to drop into its worker as is.
    body = json.dumps(build(), indent=2, ensure_ascii=False, sort_keys=False)
    return (
        "// Generated by tools/export_config.py from the Python configs -- do not edit by hand.\n"
        "// tests/lab/test_web_engine_sources.py fails when this file is stale.\n"
        f"export const DEFAULTS = {body} as const;\n"
    )


if __name__ == "__main__":
    OUT.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
