"""add standards, pitch standard_id and take goal_time_sec

Revision ID: 38d6a6f320cb
Revises: 8de0fdad60e6
Create Date: 2026-09-22 16:00:05.609514

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '38d6a6f320cb'
down_revision: str | Sequence[str] | None = '8de0fdad60e6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standards',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_standards_user_id'), 'standards', ['user_id'], unique=False)
    op.add_column('pitches', sa.Column('standard_id', sa.Uuid(), nullable=True))
    op.add_column('takes', sa.Column('goal_time_sec', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('takes', 'goal_time_sec')
    op.drop_column('pitches', 'standard_id')
    op.drop_index(op.f('ix_standards_user_id'), table_name='standards')
    op.drop_table('standards')
    # ### end Alembic commands ###
