"""add pitch and take entities

Revision ID: 09170142665e
Revises: d91f6375e513
Create Date: 2026-09-14 16:39:05.999693

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09170142665e'
down_revision: str | Sequence[str] | None = 'd91f6375e513'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pitches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('presentation_date', sa.Date(), nullable=True),
    sa.Column('best_take_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    # best_take_id 의 FK 는 takes 가 만들어진 뒤 upgrade() 끝에서 붙인다.
    # op.create_table 은 use_alter 를 무시하므로 여기 적어두면 생성되지 않는다.
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pitches_user_id'), 'pitches', ['user_id'], unique=False)
    op.create_table('presentation_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitch_id', 'version', name='uq_presentation_versions_pitch_version')
    )
    op.create_index(op.f('ix_presentation_versions_pitch_id'), 'presentation_versions', ['pitch_id'], unique=False)
    op.create_table('script_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitch_id', 'version', name='uq_script_versions_pitch_version')
    )
    op.create_index(op.f('ix_script_versions_pitch_id'), 'script_versions', ['pitch_id'], unique=False)
    op.create_table('script_slides',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('script_version_id', sa.Uuid(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('full_content', sa.Text(), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('script_version_id', 'slide_number', name='uq_script_slides_version_slide')
    )
    op.create_index(op.f('ix_script_slides_script_version_id'), 'script_slides', ['script_version_id'], unique=False)
    op.create_table('takes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pitch_id', sa.Uuid(), nullable=False),
    sa.Column('take_number', sa.Integer(), nullable=False),
    sa.Column('presentation_version_id', sa.Uuid(), nullable=False),
    sa.Column('script_version_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('script_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('event_logs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['presentation_version_id'], ['presentation_versions.id'], ),
    sa.ForeignKeyConstraint(['script_version_id'], ['script_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pitch_id', 'take_number', name='uq_takes_pitch_take_number')
    )
    op.create_index(op.f('ix_takes_pitch_id'), 'takes', ['pitch_id'], unique=False)
    op.create_table('calibrations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('take_id', sa.Uuid(), nullable=False),
    sa.Column('face_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('mic_detected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('base_volume', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('gaze_confidence', sa.Float(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calibrations_take_id'), 'calibrations', ['take_id'], unique=False)
    op.create_table('live_feedbacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('take_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('triggered_at_ms', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_feedbacks_take_id'), 'live_feedbacks', ['take_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_take_id', sa.Uuid(), nullable=False),
    sa.Column('slide_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('complete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_take_id'], ['takes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_source_take_id'), 'missions', ['source_take_id'], unique=False)
    op.create_table('take_summaries',
    sa.Column('take_id', sa.Uuid(), nullable=False),
    sa.Column('average_wpm', sa.Float(), nullable=False),
    sa.Column('filler_count', sa.Integer(), nullable=False),
    sa.Column('audience_gaze', sa.Integer(), nullable=False),
    sa.Column('slide_gaze', sa.Integer(), nullable=False),
    sa.Column('script_gaze', sa.Integer(), nullable=False),
    sa.Column('script_dependency_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('speak_accuracy', sa.Float(), nullable=False),
    sa.Column('volume', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_intermission', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['take_id'], ['takes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('take_id')
    )
    # ### end Alembic commands ###
    # pitches <-> takes 순환 참조. 양쪽 테이블이 모두 생긴 지금 FK 를 건다.
    op.create_foreign_key(
        'pitches_best_take_id_fkey', 'pitches', 'takes', ['best_take_id'], ['id']
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pitches.best_take_id 와 takes.pitch_id 가 서로를 참조한다. 순환이라 삭제
    # 순서로는 못 풀고, FK 를 먼저 떼어내야 takes 를 지울 수 있다. (use_alter 의 역방향)
    op.drop_constraint('pitches_best_take_id_fkey', 'pitches', type_='foreignkey')
    op.drop_table('take_summaries')
    op.drop_index(op.f('ix_missions_source_take_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_live_feedbacks_take_id'), table_name='live_feedbacks')
    op.drop_table('live_feedbacks')
    op.drop_index(op.f('ix_calibrations_take_id'), table_name='calibrations')
    op.drop_table('calibrations')
    op.drop_index(op.f('ix_takes_pitch_id'), table_name='takes')
    op.drop_table('takes')
    op.drop_index(op.f('ix_script_slides_script_version_id'), table_name='script_slides')
    op.drop_table('script_slides')
    op.drop_index(op.f('ix_script_versions_pitch_id'), table_name='script_versions')
    op.drop_table('script_versions')
    op.drop_index(op.f('ix_presentation_versions_pitch_id'), table_name='presentation_versions')
    op.drop_table('presentation_versions')
    op.drop_index(op.f('ix_pitches_user_id'), table_name='pitches')
    op.drop_table('pitches')
    # ### end Alembic commands ###
