"""oauth_accounts unique per provider

Revision ID: 089e4bdb0e9e
Revises: d91f6375e513
Create Date: 2026-09-13 23:44:23.400440

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '089e4bdb0e9e'
down_revision: str | Sequence[str] | None = 'd91f6375e513'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 회원당 소셜 계정 하나 -> 회원당 provider 마다 하나.
    # 'oauth_accounts_user_id_key' 는 create_oauth_accounts 마이그레이션이 이름 없이 만들어
    # Postgres 가 붙인 이름이다. 기존 행은 user_id 가 이미 유일하므로 새 제약을 바로 만족한다.
    op.drop_constraint(op.f('oauth_accounts_user_id_key'), 'oauth_accounts', type_='unique')
    op.create_unique_constraint('uq_oauth_accounts_user_provider', 'oauth_accounts', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 한 회원에 provider 가 둘 이상 붙어 있으면 실패한다. 어느 행을 지울지는 마이그레이션이 정하지 않는다.
    op.drop_constraint('uq_oauth_accounts_user_provider', 'oauth_accounts', type_='unique')
    op.create_unique_constraint(op.f('oauth_accounts_user_id_key'), 'oauth_accounts', ['user_id'])
    # ### end Alembic commands ###
