"""empty message

Revision ID: 7a545e652b8b
Revises: 17e06a675e53
Create Date: 2026-09-30 18:45:02.963698

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_git_revisions import get_down_revision


# revision identifiers, used by Alembic.
revision: str = '7a545e652b8b'
down_revision: str | Sequence[str] | None = get_down_revision(revision)
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('upper_deviation', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('pitches', sa.Column('lower_deviation', sa.Integer(), nullable=False, server_default='0'))
    op.create_unique_constraint('uq_standards_pitch_version', 'standards', ['pitch_id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_standards_pitch_version', 'standards', type_='unique')
    op.drop_column('pitches', 'lower_deviation')
    op.drop_column('pitches', 'upper_deviation')
    # ### end Alembic commands ###
