"""add position to standards

Revision ID: 2ed4bcd8c378
Revises: 478bf4748f21
Create Date: 2026-10-07 15:55:02.065656

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_git_revisions import get_down_revision


# revision identifiers, used by Alembic.
revision: str = '2ed4bcd8c378'
down_revision: str | Sequence[str] | None = get_down_revision(revision)
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standards', sa.Column('position', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('uq_standards_pitch_version'), 'standards', type_='unique')
    op.create_unique_constraint('uq_standards_pitch_version_position', 'standards', ['pitch_id', 'version', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_standards_pitch_version_position', 'standards', type_='unique')
    op.create_unique_constraint(op.f('uq_standards_pitch_version'), 'standards', ['pitch_id', 'version'], postgresql_nulls_not_distinct=False)
    op.drop_column('standards', 'position')
    # ### end Alembic commands ###
