"""add replaced_by_id to refresh_tokens

Revision ID: 0cf6b0be3f63
Revises: 2ed4bcd8c378
Create Date: 2026-10-07 20:45:06.991706

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from alembic_git_revisions import get_down_revision


# revision identifiers, used by Alembic.
revision: str = '0cf6b0be3f63'
down_revision: str | Sequence[str] | None = get_down_revision(revision)
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('replaced_by_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('refresh_tokens_replaced_by_id_fkey', 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('refresh_tokens_replaced_by_id_fkey', 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'replaced_by_id')
    # ### end Alembic commands ###
